<?php
/**
 * Header Tab For Theme Option.
 *
 * @package Brando
 */
?>
<?php
$brando_live_site_url = 'http://wpdemos.themezaa.com/brando';
$this->sections[] = array(
    'icon' => 'fa fa-tint',
    'title' => esc_html__('Color Settings', 'brando'),
    'desc' => sprintf(__('Configure your brand colors <br/> Please ', 'brando')).'<a href="'.esc_url( $brando_live_site_url ).'/documentation/plugins/options/theme-options/color-settings/" target="_blank">'.esc_html__('click here', 'brando').'</a>'.esc_html__( ' to check our infographics to better understand which color is used where in the theme and hence it can be easy for you to change colors in your website using below options.', 'brando'),
    'fields' => array(
    		array(
	            'id'        => 'opt-accordion-begin-general',
	            'type'      => 'accordion',
	            'title'     => esc_html__('Background Color', 'brando'),
	            'subtitle'  => esc_html__('Set background color', 'brando'),
	            'position'  => 'start',
	        ),
            array(
                'id'       => 'bg_body_color',
                'type'     => 'color',
                'title'    => '<div class="color-box"></div>'.esc_html__( 'Body Background', 'brando' ),
                'output' => array('background' => 'body'),
            ),
          	array(
                'id'       => 'bg_white_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#fff"></div>'.esc_html__( 'White Background', 'brando' ),
                'default'  => '#fff',
                'output' => array('background' => '.bg-white'),
            ),
            array(
                'id'       => 'bg_black_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#000"></div>'.esc_html__( 'Black Background', 'brando' ),
                'default'  => '#000',
                'output' => array('background' => '.bg-black'),
            ),
            array(
                'id'       => '.bg_dark_gray_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#252525"></div>'.esc_html__( 'Dark Gray Background', 'brando' ),
                'default'  => '#252525',
                'output' => array('background' => '.bg-dark-gray'),
            ),
            array(
                'id'       => 'bg_mid_gray_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#d4d4d4"></div>'.esc_html__( 'Mid Gray Background', 'brando' ),
                'default'  => '#d4d4d4',
                'output' => array('background' => '.bg-mid-gray'),
            ),
            array(
                'id'       => 'bg_mid_gray2_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#b2b2b2"></div>'.esc_html__( 'Mid Gray2 Background', 'brando' ),
                'default'  => '#b2b2b2',
                'output' => array('background' => '.bg-mid-gray2'),
            ),
            array(
                'id'       => 'bg_mid_gray3_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#e2e2e2"></div>'.esc_html__( 'Mid Gray3 Background', 'brando' ),
                'default'  => '#e2e2e2',
                'output' => array('background' => '.bg-mid-gray3'),
            ),
            array(
                'id'       => 'bg_light_gray_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#f7f7f7"></div>'.esc_html__( 'Light Gray Background', 'brando' ),
                'default'  => '#f7f7f7',
                'output' => array('background' => '.bg-light-gray'),
            ),
            array(
                'id'       => 'bg_gray_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#f6f6f6"></div>'.esc_html__( 'Gray Background', 'brando' ),
                'default'  => '#f6f6f6',
                'output' => array('background' => '.bg-gray'),
            ),
            array(
                'id'       => 'bg_yellow_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#e6af2a"></div>'.esc_html__( 'Yellow Background', 'brando' ),
                'default'  => '#e6af2a',
                'output' => array('background' => '.bg-yellow'),
            ),
            array(
                'id'       => 'bg_light_yellow_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#f8f7f5"></div>'.esc_html__( 'Light Yellow Background', 'brando' ),
                'default'  => '#f8f7f5',
                'output' => array('background' => '.bg-light-yellow'),
            ),
            array(
                'id'       => 'bg_deep_yellow_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#c8a64b"></div>'.esc_html__( 'Deep Yellow Background', 'brando' ),
                'default'  => '#c8a64b',
                'output' => array('background' => '.bg-deep-yellow'),
            ),
            array(
                'id'       => 'bg_golden_yellow_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#ffd800"></div>'.esc_html__( 'Golden Yellow Background', 'brando' ),
                'default'  => '#ffd800',
                'output' => array('background' => '.bg-golden-yellow'),
            ),
            array(
                'id'       => 'bg_fast_yellow_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#fdd947"></div>'.esc_html__( 'Fast Yellow Background', 'brando' ),
                'default'  => '#fdd947',
                'output' => array('background' => '.bg-fast-yellow'),
            ),
            array(
                'id'       => 'bg_yellow_ochre_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#997546"></div>'.esc_html__( 'Yellow Ochre Background', 'brando' ),
                'default'  => '#997546',
                'output' => array('background' => '.bg-yellow-ochre'),
            ),
            array(
                'id'       => 'bg_brown_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#614c45"></div>'.esc_html__( 'Brown Background', 'brando' ),
                'default'  => '#614c45',
                'output' => array('background' => '.bg-brown'),
            ),
            array(
                'id'       => 'bg_deep_brown_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#544441"></div>'.esc_html__( 'Deep Brown Background', 'brando' ),
                'default'  => '#544441',
                'output' => array('background' => '.bg-deep-brown'),
            ),
            array(
                'id'       => 'bg_orange_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#c24742"></div>'.esc_html__( 'Orange Background', 'brando' ),
                'default'  => '#c24742',
                'output' => array('background' => '.bg-orange'),
            ),
            array(
                'id'       => 'bg_deep_orange_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#d66e4a"></div>'.esc_html__( 'Deep Orange Background', 'brando' ),
                'default'  => '#d66e4a',
                'output' => array('background' => '.bg-deep-orange'),
            ),
            array(
                'id'       => 'bg_fast_orange_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#ff513b"></div>'.esc_html__( 'Fast Orange Background', 'brando' ),
                'default'  => '#ff513b',
                'output' => array('background' => '.bg-fast-orange'),
            ),
            array(
                'id'       => 'bg_pink_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#c2345f"></div>'.esc_html__( 'Deep Yellow Background', 'brando' ),
                'default'  => '#c2345f',
                'output' => array('background' => '.bg-pink'),
            ),
            array(
                'id'       => 'bg_deep_red_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#dc3535"></div>'.esc_html__( 'Deep Red Background', 'brando' ),
                'default'  => '#dc3535',
                'output' => array('background' => '.bg-deep-red'),
            ),
            array(
                'id'       => 'bg_crimson_red_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#00BED6"></div>'.esc_html__( 'Crimson Red Background', 'brando' ),
                'default'  => '#00BED6',
                'output' => array('background' => '.bg-crimson-red'),
            ),
            array(
                'id'       => 'bg_deep_pink_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#e53878"></div>'.esc_html__( 'Deep Pink Background', 'brando' ),
                'default'  => '#e53878',
                'output' => array('background' => '.bg-deep-pink'),
            ),
            array(
                'id'       => 'bg_light_pink_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#dc378e"></div>'.esc_html__( 'Light Pink Background', 'brando' ),
                'default'  => '#dc378e',
                'output' => array('background' => '.bg-light-pink'),
            ),
            array(
                'id'       => 'bg_deep_pink_dark_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#e15276"></div>'.esc_html__( 'Deep Pink Dark Background', 'brando' ),
                'default'  => '#e15276',
                'output' => array('background' => '.bg-deep-pink-dark'),
            ),
            array(
                'id'       => '.bg-fast-pink_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#ff1a56"></div>'.esc_html__( 'Fast Pink Background', 'brando' ),
                'default'  => '#ff1a56',
                'output' => array('background' => '.bg-fast-pink'),
            ),
            array(
                'id'       => 'bg_fast_pink_dark_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#ef106e"></div>'.esc_html__( 'Fast Pink Dark Background', 'brando' ),
                'default'  => '#ef106e',
                'output' => array('background' => '.bg-fast-pink-dark'),
            ),
            array(
                'id'       => 'bg_magenta_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#d94378"></div>'.esc_html__( 'Magenta Background', 'brando' ),
                'default'  => '#d94378',
                'output' => array('background' => '.bg-magenta'),
            ),
            array(
                'id'       => 'bg_dark_green_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#60a532"></div>'.esc_html__( 'Dark Green Background', 'brando' ),
                'default'  => '#60a532',
                'output' => array('background' => '.bg-dark-green'),
            ),
            array(
                'id'       => 'bg_fast_green_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#00ff97"></div>'.esc_html__( 'Fast Green Background', 'brando' ),
                'default'  => '#00ff97',
                'output' => array('background' => '.bg-fast-green'),
            ),
            array(
                'id'       => 'bg_deep_green_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#1acd7b"></div>'.esc_html__( 'Deep Green Background', 'brando' ),
                'default'  => '#1acd7b',
                'output' => array('background' => '.bg-deep-green'),
            ),
            array(
                'id'       => 'bg_deep_green2_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#7ebaa1"></div>'.esc_html__( 'Deep Green2 Background', 'brando' ),
                'default'  => '#7ebaa1',
                'output' => array('background' => '.bg-deep-green2'),
            ),
            array(
                'id'       => 'bg_deep_green_dark_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#04b966"></div>'.esc_html__( 'Deep Green Dark Background', 'brando' ),
                'default'  => '#04b966',
                'output' => array('background' => '.bg-deep-green-dark'),
            ),
            array(
                'id'       => 'bg_deep_green_dark2_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#6ad5a7"></div>'.esc_html__( 'Deep Green Dark2 Background', 'brando' ),
                'default'  => '#6ad5a7',
                'output' => array('background' => '.bg-deep-green-dark2'),
            ),
            array(
                'id'       => 'bg_deep_green_dark3_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#62a486"></div>'.esc_html__( 'Deep Green Dark3 Background', 'brando' ),
                'default'  => '#62a486',
                'output' => array('background' => '.bg-deep-green-dark3'),
            ),
            array(
                'id'       => 'bg_transparent_green_color',
                'type'     => 'color_rgba',
                'title'    => '<div class="color-box" style="background-color:rgba(0,255,151,.5)"></div>'.esc_html__( 'Transparent Green Background', 'brando' ),
                'default'  =>  array( 'color' => '#00ff97', 'alpha' => '0.5' ),
                'output' => array('background' => '.bg-transparent-green'),
            ),
            array(
                'id'       => 'bg_fast_blue_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#00efff"></div>'.esc_html__( 'Fast Blue Background', 'brando' ),
                'default'  => '#00efff',
                'output' => array('background' => '.bg-fast-blue'),
            ),
            array(
                'id'       => 'bg_dark_blue_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#1e2126"></div>'.esc_html__( 'Dark Blue Background', 'brando' ),
                'default'  => '#1e2126',
                'output' => array('background' => '.bg-dark-blue'),
            ),
            array(
                'id'       => 'bg_deep_blue_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#2283d4"></div>'.esc_html__( 'Deep Blue Background', 'brando' ),
                'default'  => '#2283d4',
                'output' => array('background' => '.bg-deep-blue'),
            ),
            array(
                'id'       => 'bg_deep_blue2_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#131d43"></div>'.esc_html__( 'Deep Blue2 Background', 'brando' ),
                'default'  => '#131d43',
                'output' => array('background' => '.bg-deep-blue2'),
            ),
            array(
                'id'       => 'bg_deep_blue3_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#1d2127"></div>'.esc_html__( 'Deep Blue3 Background', 'brando' ),
                'default'  => '#1d2127',
                'output' => array('background' => '.bg-deep-blue3'),
            ),
            array(
                'id'       => 'bg_transparent_deep_blue_color',
                'type'     => 'color_rgba',
                'title'    => '<div class="color-box" style="background-color:rgba(17,116,198,.9)"></div>'.esc_html__( 'Transparent Deep Blue Background', 'brando' ),
                'default'  =>  array( 'color' => '#1174c6', 'alpha' => '0.9' ),
                'output' => array('background' => '.bg-transparent-deep-blue'),
            ),
            array(
                'id'       => 'bg_turquoise_blue_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#93e4cf"></div>'.esc_html__( 'Turquoise Blue Background', 'brando' ),
                'default'  => '#93e4cf',
                'output' => array('background' => '.bg-turquoise-blue'),
            ),
            array(
                'id'       => 'bg_deep_blue_dark_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#1d6cae"></div>'.esc_html__( 'Deep Blue Dark Background', 'brando' ),
                'default'  => '#1d6cae',
                'output' => array('background' => '.bg-deep-blue-dark'),
            ),
            array(
                'id'       => 'bg_transparent_blue_color',
                'type'     => 'color_rgba',
                'title'    => '<div class="color-box" style="background-color:rgba(0,239,255,.5)"></div>'.esc_html__( 'Transparent Blue Background', 'brando' ),
                'default'  =>  array( 'color' => '#00efff', 'alpha' => '0.5' ),
                'output' => array('background' => '.bg-transparent-blue'),
            ),
            array(
                'id'       => 'bg_violet_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#6c407e"></div>'.esc_html__( 'Violet Background', 'brando' ),
                'default'  => '#6c407e',
                'output' => array('background' => '.bg-violet'),
            ),
            array(
	            'id'        => 'opt-accordion-end-general',
	            'type'      => 'accordion',
	            'position'  => 'end'
	        ),

            /* Header Color */

            array(
                'id'        => 'opt-accordion-begin-general',
                'type'      => 'accordion',
                'title'     => esc_html__('Header Color', 'brando'),
                'subtitle'  => esc_html__('Set header color', 'brando'),
                'position'  => 'start',
            ),
            array(
                'id'       => 'bg_nav_menu',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#000"></div>'.esc_html__( 'Header Background', 'brando' ),
                'default'  => '#000',
                'output' => array('background' => 'nav.shrink'),
            ),
            array(
                'id'       => 'bg_pull_nav_menu',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#fff"></div>'.esc_html__( 'Pull Header Background', 'brando' ),
                'default'  => '#fff',
                'output' => array('background' => '.menu-wrap'),
            ),
            array(
                'id'       => 'bg_center_logo_nav_menu',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#93e4cf"></div>'.esc_html__( 'Center Logo Header Background', 'brando' ),
                'default'  => '#93e4cf',
                'output' => array('background' => '.center-logo-header, .shrink.center-logo-header'),
            ),
            array(
                'id'       => 'bg_transparent_nav_menu',
                'type'     => 'color_rgba',
                'title'    => '<div class="color-box" style="background-color:rgba(0, 0, 0, 0.7)"></div>'.esc_html__( 'Transparent Header Background', 'brando' ),
                'default'  =>  array( 'color' => '#000', 'alpha' => '0.7' ),
                'output' => array('background' => '.transparent-header.shrink'),
            ),
            array(
                'id'       => 'bg_sidebar_nav_menu',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#fff"></div>'.esc_html__( 'Sidebar Header Background', 'brando' ),
                'default'  => '#fff',
                'output' => array('background' => '.sidebar-nav, nav.shrink.sidebar-nav'),
            ),
            array(
                'id'       => 'bg_white_nav_menu',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#fff"></div>'.esc_html__( 'White Header Background', 'brando' ),
                'default'  => '#fff',
                'output' => array('background' => '.header-white, .header-white.shrink'),
            ),
            array(
                'id'       => 'bg_without_border_nav_menu',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#000"></div>'.esc_html__( 'Without Border Header Background', 'brando' ),
                'default'  => '#000',
                'output' => array('background' => 'nav.without-border.shrink'),
            ),
            array(
                'id'       => 'bg_dropdown_menu',
                'type'     => 'color',
                'title'    => '<div class="color-box"></div>'.esc_html__( 'Dropdown Menu Color', 'brando' ),
                'output' => array('background' => '.navbar-nav li ul li, .pull-menu .navbar-nav li > ul li, .center-logo-header .navbar-nav li > ul li, .sidebar-nav .navbar-nav li > ul li'),
            ),
            array(
                'id'        => 'opt-accordion-end-general',
                'type'      => 'accordion',
                'position'  => 'end'
            ),

            /* Text Color */

	        array(
	            'id'        => 'opt-accordion-begin-general',
	            'type'      => 'accordion',
	            'title'     => esc_html__('Text Color', 'brando'),
	            'subtitle'  => esc_html__('Set text color', 'brando'),
	            'position'  => 'start',
	        ),
	        array(
                'id'       => 'body_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#626262"></div>'.esc_html__( 'Body Color', 'brando' ),
                'default'  => '#626262',
                'output' => array('body'),
            ),
            array(
                'id'       => 'link_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#626262"></div>'.esc_html__( 'Link Color', 'brando' ),
                'default'  => '#626262',
                'output' => array('a'),
            ),
            array(
                'id'       => 'link_hover_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#272727"></div>'.esc_html__( 'Link Hover Color', 'brando' ),
                'default'  => '#272727',
                'output' => array('a:hover'),
            ),
            array(
                'id'       => 'icon_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#9a9a9a"></div>'.esc_html__( 'Icon Color', 'brando' ),
                'default'  => '#9a9a9a',
                'output' => array('i'),
            ),
            array(
                'id'       => 'white_text_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#fff"></div>'.esc_html__( 'White Text Color', 'brando' ),
                'default'  => '#fff',
                'output' => array('.white-text'),
            ),
            array(
                'id'       => 'black_text_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#000"></div>'.esc_html__( 'Black Text Color', 'brando' ),
                'default'  => '#000',
                'output' => array('.black-text'),
            ),
            array(
                'id'       => 'gray_text_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#626262"></div>'.esc_html__( 'Gray Text Color', 'brando' ),
                'default'  => '#626262',
                'output' => array('.gray-text'),
            ),
            array(
                'id'       => 'light_gray_text_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#ababab"></div>'.esc_html__( 'Light Gray Text Color', 'brando' ),
                'default'  => '#ababab',
                'output' => array('.light-gray-text'),
            ),
            array(
                'id'       => 'light_gray_text2_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#c5c5c5"></div>'.esc_html__( 'Light Gray Text2 Color', 'brando' ),
                'default'  => '#c5c5c5',
                'output' => array('.light-gray-text2'),
            ),
            array(
                'id'       => 'medium_gray_text_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#929292"></div>'.esc_html__( 'Medium Gray Text Color', 'brando' ),
                'default'  => '#929292',
                'output' => array('.medium-gray-text'),
            ),
            array(
                'id'       => 'dark_gray_text_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#373737"></div>'.esc_html__( 'Dark Gray Text Color', 'brando' ),
                'default'  => '#373737',
                'output' => array('.dark-gray-text'),
            ),
            array(
                'id'       => 'deep_gray_text_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#404040"></div>'.esc_html__( 'Deep Gray Text Color', 'brando' ),
                'default'  => '#404040',
                'output' => array('.deep-gray-text'),
            ),
            array(
                'id'       => 'deep_light_gray_text_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#878787"></div>'.esc_html__( 'Deep Light Gray Text Color', 'brando' ),
                'default'  => '#878787',
                'output' => array('.deep-light-gray-text'),
            ),
            array(
                'id'       => 'magenta_text_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#d94378"></div>'.esc_html__( 'Magenta Text Color', 'brando' ),
                'default'  => '#d94378',
                'output' => array('.magenta-text'),
            ),
            array(
                'id'       => 'orange_text_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#ff513b"></div>'.esc_html__( 'Orange Text Color', 'brando' ),
                'default'  => '#ff513b',
                'output' => array('.orange-text'),
            ),
            array(
                'id'       => 'deep_orange_text_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#d66e4a"></div>'.esc_html__( 'Deep Orange Text Color', 'brando' ),
                'default'  => '#d66e4a',
                'output' => array('.deep-orange-text'),
            ),
            array(
                'id'       => 'deep_red_text_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#e75e50"></div>'.esc_html__( 'Deep Red Text Color', 'brando' ),
                'default'  => '#e75e50',
                'output' => array('.deep-red-text'),
            ),
            array(
                'id'       => 'crimson_red_text_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#00BED6"></div>'.esc_html__( 'Crimson Red Text Color', 'brando' ),
                'default'  => '#00BED6',
                'output' => array('.crimson-red-text'),
            ),
            array(
                'id'       => 'deep_pink_dark_text_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#e15276"></div>'.esc_html__( 'Deep Pink Dark Text Color', 'brando' ),
                'default'  => '#e15276',
                'output' => array('.deep-pink-dark-text'),
            ),
            array(
                'id'       => 'fast_pink_text_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#ff1a56"></div>'.esc_html__( 'Fast Pink Text Color', 'brando' ),
                'default'  => '#ff1a56',
                'output' => array('.fast-pink-text'),
            ),
            array(
                'id'       => 'fast_pink_text_dark_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#ef106e"></div>'.esc_html__( 'Fast Pink Text Dark Color', 'brando' ),
                'default'  => '#ef106e',
                'output' => array('.fast-pink-text-dark'),
            ),
            array(
                'id'       => 'yellow_text_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#ffcd00"></div>'.esc_html__( 'Yellow Text Color', 'brando' ),
                'default'  => '#ffcd00',
                'output' => array('.yellow-text'),
            ),
            array(
                'id'       => 'fast_yellow_text_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#fdd947"></div>'.esc_html__( 'Fast Yellow Text Color', 'brando' ),
                'default'  => '#fdd947',
                'output' => array('.fast-yellow-text'),
            ),
            array(
                'id'       => 'brown_text_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#614c45"></div>'.esc_html__( 'Brown Text Color', 'brando' ),
                'default'  => '#614c45',
                'output' => array('.brown-text'),
            ),
            array(
                'id'       => 'deep_yellow_text_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#c8a64b"></div>'.esc_html__( 'Deep Yellow Text Color', 'brando' ),
                'default'  => '#c8a64b',
                'output' => array('.deep-yellow-text'),
            ),
            array(
                'id'       => 'dark_blue_text_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#1e2126"></div>'.esc_html__( 'Dark Blue Text Color', 'brando' ),
                'default'  => '#1e2126',
                'output' => array('.dark-blue-text'),
            ),
            array(
                'id'       => 'deep_blue_text_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#2283d4"></div>'.esc_html__( 'Deep Blue Text Color', 'brando' ),
                'default'  => '#2283d4',
                'output' => array('.deep-blue-text'),
            ),
            array(
                'id'       => 'turquoise_blue_text_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#85d4c0"></div>'.esc_html__( 'Turquoise Blue Text Color', 'brando' ),
                'default'  => '#85d4c0',
                'output' => array('.turquoise-blue-text'),
            ),
            array(
                'id'       => 'transparent_blue_text_color',
                'type'     => 'color_rgba',
                'title'    => '<div class="color-box" style="background-color:rgba(0,239,255,.5)"></div>'.esc_html__( 'Transparent Blue Text Color', 'brando' ),
                'default'  =>  array( 'color' => '#00ff97', 'alpha' => '0.5' ),
                'output' => array('.transparent-blue-text'),
            ),
            array(
                'id'       => 'fast_green_text_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#85eea5"></div>'.esc_html__( 'Fast Green Text Color', 'brando' ),
                'default'  => '#85eea5',
                'output' => array('.fast-green-text'),
            ),
            array(
                'id'       => 'deep_green_text_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#1acd7b"></div>'.esc_html__( 'Deep Green Text Color', 'brando' ),
                'default'  => '#1acd7b',
                'output' => array('.deep-green-text'),
            ),
            array(
                'id'       => 'deep_green_dark2_text_color',
                'type'     => 'color',
                'title'    => '<div class="color-box" style="background-color:#6ad5a7"></div>'.esc_html__( 'Deep Green Dark2 Text Color', 'brando' ),
                'default'  => '#6ad5a7',
                'output' => array('.deep-green-dark2-text'),
            ),
            array(
                'id'       => 'transparent_green_text_color',
                'type'     => 'color_rgba',
                'title'    => '<div class="color-box" style="background-color:rgba(0,255,151,.5)"></div>'.esc_html__( 'Transparent Green Text Color', 'brando' ),
                'default'  =>  array( 'color' => '#00ff97', 'alpha' => '0.5' ),
                'output'   => array('.transparent-green-text'),
            ),
	        array(
	            'id'        => 'opt-accordion-end-general',
	            'type'      => 'accordion',
	            'position'  => 'end'
	        ),
    )
);
?>