<?php
/**
 * Brando Animation Styles For VC Fields.
 *
 * @package Brando
 */
?>
<?php 
if( !function_exists('brando_animation_style')) {
  function brando_animation_style() {
  	$output = '';
    $output = array(__('no style', 'brando-addons') => '',
    				__('bounce', 'brando-addons') => 'bounce',
    				__('flash', 'brando-addons') => 'flash',
    				__('pulse', 'brando-addons') => 'pulse',
    				__('rubberBand', 'brando-addons') => 'rubberBand',
    				__('shake', 'brando-addons') => 'shake',
    				__('swing', 'brando-addons') => 'swing',
    				__('tada', 'brando-addons') => 'tada',
    				__('wobble', 'brando-addons') => 'wobble',
    				__('jello', 'brando-addons') => 'jello',
    				__('bounceIn', 'brando-addons') => 'bounceIn',
    				__('bounceInDown', 'brando-addons') => 'bounceInDown',
    				__('bounceInLeft', 'brando-addons') => 'bounceInLeft',
    				__('bounceInRight', 'brando-addons') => 'bounceInRight',
    				__('bounceInUp', 'brando-addons') => 'bounceInUp',
    				__('bounceOut', 'brando-addons') => 'bounceOut',
    				__('bounceOutDown', 'brando-addons') => 'bounceOutDown',
    				__('bounceOutLeft', 'brando-addons') => 'bounceOutLeft',
    				__('bounceOutRight', 'brando-addons') => 'bounceOutRight',
    				__('bounceOutUp', 'brando-addons') => 'bounceOutUp',
    				__('fadeIn', 'brando-addons') => 'fadeIn',
    				__('fadeInDown', 'brando-addons') => 'fadeInDown',
    				__('fadeInDownBig', 'brando-addons') => 'fadeInDownBig',
    				__('fadeInLeft', 'brando-addons') => 'fadeInLeft',
    				__('fadeInLeftBig', 'brando-addons') => 'fadeInLeftBig',
    				__('fadeInRight', 'brando-addons') => 'fadeInRight',
    				__('fadeInRightBig', 'brando-addons') => 'fadeInRightBig',
    				__('fadeInUp', 'brando-addons') => 'fadeInUp',
    				__('fadeInUpBig', 'brando-addons') => 'fadeInUpBig',
    				__('fadeOut', 'brando-addons') => 'fadeOut',
    				__('fadeOutDown', 'brando-addons') => 'fadeOutDown',
    				__('fadeOutDownBig', 'brando-addons') => 'fadeOutDownBig',
					__('fadeOutLeft', 'brando-addons') => 'fadeOutLeft',
					__('fadeOutLeftBig', 'brando-addons') => 'fadeOutLeftBig',
					__('fadeOutRight', 'brando-addons') => 'fadeOutRight',
					__('fadeOutRightBig', 'brando-addons') => 'fadeOutRightBig',
					__('fadeOutUp', 'brando-addons') => 'fadeOutUp',
					__('fadeOutUpBig', 'brando-addons') => 'fadeOutUpBig',
					__('flipInX', 'brando-addons') => 'flipInX',
					__('flipInY', 'brando-addons') => 'flipInY',
					__('flipOutX', 'brando-addons') => 'flipOutX',
					__('flipOutY', 'brando-addons') => 'flipOutY',
					__('lightSpeedIn', 'brando-addons') => 'lightSpeedIn',
					__('lightSpeedOut', 'brando-addons') => 'lightSpeedOut',
					__('rotateIn', 'brando-addons') => 'rotateIn',
					__('rotateInDownLeft', 'brando-addons') => 'rotateInDownLeft',
					__('rotateInDownRight', 'brando-addons') => 'rotateInDownRight',
					__('rotateInUpLeft', 'brando-addons') => 'rotateInUpLeft',
					__('rotateInUpRight', 'brando-addons') => 'rotateInUpRight',
					__('rotateOut', 'brando-addons') => 'rotateOut',
					__('rotateOutDownLeft', 'brando-addons') => 'rotateOutDownLeft',
					__('rotateOutDownRight', 'brando-addons') => '',
					__('rotateOutUpLeft', 'brando-addons') => 'rotateOutDownRight',
					__('rotateOutUpRight', 'brando-addons') => 'rotateOutUpRight',
					__('hinge', 'brando-addons') => 'hinge',
					__('rollIn', 'brando-addons') => 'rollIn',
					__('rollOut', 'brando-addons') => 'rollOut',
					__('zoomIn', 'brando-addons') => 'zoomIn',
					__('zoomInDown', 'brando-addons') => 'zoomInDown',
					__('zoomInLeft', 'brando-addons') => 'zoomInLeft',
					__('zoomInRight', 'brando-addons') => 'zoomInRight',
					__('zoomInUp', 'brando-addons') => 'zoomInUp',
					__('zoomOut', 'brando-addons') => 'zoomOut',
					__('zoomOutDown', 'brando-addons') => 'zoomOutDown',
					__('zoomOutLeft', 'brando-addons') => 'zoomOutLeft',
					__('zoomOutRight', 'brando-addons') => 'zoomOutRight',
					__('zoomOutUp', 'brando-addons') => 'zoomOutUp',
					__('slideInDown', 'brando-addons') => 'slideInDown',
					__('slideInLeft', 'brando-addons') => 'slideInLeft',
					__('slideInRight', 'brando-addons') => 'slideInRight',
					__('slideInUp', 'brando-addons') => 'slideInUp',
					__('slideOutDown', 'brando-addons') => 'slideOutDown',
					__('slideOutLeft', 'brando-addons') => 'slideOutLeft',
    			    __('slideOutRight', 'brando-addons') => 'slideOutRight',
    			    __('slideOutUp', 'brando-addons') => 'slideOutUp',
    			    );
    return $output;
  }
}
?>